datagrid:
    pmanager-pdftemplates:
        extended_entity_name: '%oro_user.entity.class%'
        options:
            entityHint: PDF template
        source:
            type: orm
            acl_resource: pmanager_template_index
            query:
                select:
                    - pt.id
                    - pt.entityName
                    - pt.name
                    - pt.description
                    - pt.type
                    - pt.isSystem
                from:
                    - { table: %ibnab_pmanager.pdftemplate.entity.class%, alias: pt }

        columns:
            #entityName:
                 #label:          ibnab.pmanager.pdftemplate.entity_name.label
                 #type:           twig
                 #template:       OroEntityBundle:Datagrid:Property/entity.html.twig
                 #frontend_type:  html
            name:
                label:          ibnab.pmanager.pdftemplate.name.label
            description:
                label:          ibnab.pmanager.pdftemplate.description.label
            type:
                label:          ibnab.pmanager.pdftemplate.type.label
            isSystem:
                label:          ibnab.pmanager.pdftemplate.is_system.label
        properties:
            id: ~
            update_link:
                type: url
                route: pmanager_template_update
                params: [ id ]
            clone_link:
                type: url
                route: pmanager_template_clone
                params: [ id ]
            delete_link:
                type: url
                route: pmanager_template_delete
                params: [ id ]

        filters:
            columns:
                entityName:
                    type:      choice
                    data_name: pt.entityName
                    null_value: _empty_
                    options:
                        field_options:
                            multiple:       true
                name:
                    type:      string
                    data_name: pt.name
                type:
                    type:            choice
                    data_name:       pt.type

                isSystem:
                    type:           boolean
                    data_name:      pt.isSystem

        sorters:
            columns:
                name:     { data_name: pt.name }
                type:     { data_name: pt.type }
                isSystem: { data_name: pt.isSystem }

        actions:
            update:
                type:         navigate
                label:        oro.grid.action.update
                link:         update_link
                icon:         edit
                acl_resource: pmanager_template_update
                rowAction:    true
            clone:
                type:         navigate
                label:        oro.grid.action.clone
                link:         clone_link
                icon:         copy
                acl_resource: pmanager_template_create
            delete:
                type:         delete
                label:        oro.grid.action.delete
                acl_resource: pmanager_template_delete
                icon:         trash
                link:         delete_link